name: Run UI Regression Tests

on:
  push:
    branches: [main]
    paths:
      - "components/ui/**"
      - "packages/browser-test-runner/**"
      - "packages/test-runner/**"
      - "packages/showcase/**"
  pull_request:
    branches: [main]
    paths:
      - "components/ui/**"
      - "packages/browser-test-runner/**"
      - "packages/test-runner/**"
      - "packages/showcase/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - name: Install packages
        run: pnpm install
      - name: Build all dependencies
        run: pnpm build:deps
      - name: Install Playwright
        working-directory: packages/browser-test-runner
        run: pnpm playwright install --with-deps
      - name: Run showcase in background
        run: |
          pnpm showcase &
      - name: Run tests
        working-directory: packages/browser-test-runner
        run: pnpm playwright test regression
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: packages/browser-test-runner/playwright-report
